### ISSUE TITLE
class SpotWorker(pytak.MessageWorker): AttributeError: module 'pytak' has no attribute 'MessageWorker'

### ISSUE THREAD

**Issue by VA2XJM** [ampledata/spotcot#11]
```
user@ve2atu-tak:~/cot_conf$ python3 -m pip install pytak
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pytak in /home/user/.local/lib/python3.9/site-packages (5.3.1)
user@ve2atu-tak:~/cot_conf$ python3 -m pip install spotcot
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: spotcot in /home/user/.local/lib/python3.9/site-packages (2.0.2)
Requirement already satisfied: aiohttp in /home/user/.local/lib/python3.9/site-packages (from spotcot) (3.8.3)
Requirement already satisfied: pytak>=3.0.0 in /home/user/.local/lib/python3.9/site-packages (from spotcot) (5.3.1)
Requirement already satisfied: pycot>=2.5.0 in /home/user/.local/lib/python3.9/site-packages (from spotcot) (2.5.0)
Requirement already satisfied: gexml>=1.0.0 in /home/user/.local/lib/python3.9/site-packages (from pycot>=2.5.0->spotcot) (1.2.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /home/user/.local/lib/python3.9/site-packages (from aiohttp->spotcot) (2.1.1)
Requirement already satisfied: frozenlist>=1.1.1 in /home/user/.local/lib/python3.9/site-packages (from aiohttp->spotcot) (1.3.1)
Requirement already satisfied: yarl<2.0,>=1.0 in /home/user/.local/lib/python3.9/site-packages (from aiohttp->spotcot) (1.8.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/user/.local/lib/python3.9/site-packages (from aiohttp->spotcot) (6.0.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.9/dist-packages (from aiohttp->spotcot) (4.0.2)
Requirement already satisfied: attrs>=17.3.0 in /home/user/.local/lib/python3.9/site-packages (from aiohttp->spotcot) (22.1.0)
Requirement already satisfied: aiosignal>=1.1.2 in /home/user/.local/lib/python3.9/site-packages (from aiohttp->spotcot) (1.2.0)
Requirement already satisfied: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.0->aiohttp->spotcot) (2.10)
user@ve2atu-tak:~/cot_conf$ spotcot -U tcp://127.0.0.1:8088 -S 3600 -k 1B6bVm3kSdliM5vCaVczIihzq7li82aM9 -i 180 -p HAMSpot819
Traceback (most recent call last):
  File "/home/user/.local/bin/spotcot", line 5, in <module>
    from spotcot.commands import cli
  File "/home/user/.local/lib/python3.9/site-packages/spotcot/__init__.py", line 21, in <module>
    from .classes import SpotWorker  # NOQA
  File "/home/user/.local/lib/python3.9/site-packages/spotcot/classes.py", line 23, in <module>
    class SpotWorker(pytak.MessageWorker):
AttributeError: module 'pytak' has no attribute 'MessageWorker'
```
Everything is installed through PIP.

Python 3.9 and Debian 11.

**Comment by ampledata** [comment]
That's odd, thanks for filing.

Work around: python3 -m pip install -U pytak


--
Greg Albrecht ***@***.***> W2GMD
EMT. Disaster & Emergency Information Communications Technology (ICT)
Specialist.
Mobile: 1-415-598-8226
https://ampledata.org/

**Comment by VA2XJM** [comment]
Exactly the same. I will try to investigate it further tonight when the kids are out to bed.

**Comment by VA2XJM** [comment]
@ampledata I can see data into the XML feed, but I am wondering if the fact that I have my hand on a Spot Trace device instead of a messaging device. If you agree, I can send you the XML feed ID through Discord so you can check on your side...
